### ISSUE TITLE
Inference script

### ISSUE THREAD

**Issue by isty2e** [ACE-KAIST/PIGNet#2]
Currently, it is not straightforward to run inference on an arbitrary, user-defined protein-ligand complex. [The old repository](https://github.com/jaechanglim/DTI_PDBbind) is helpful in this regard, but it would seem that additional works are required. Is there any plan in this direction?

**Comment by mseok** [comment]
Sorry for late reply.
You can refer to the files in `casf2016_benchmark` directory.
- `casf2016_benchmark/scoring_power.py`: benchmark the model scoring power.
- `casf2016_benchmark/ranking_power.py`: benchmark the model ranking power.
- `casf2016_benchmark/docking_power.py`: benchmark the model docking power. You may additionally need rmsd values of CASF-2016 docked complexes, which is in `casf2016_benchmark/decoys_docking_rmsd`.
- `casf2016_benchmark/scoring_power.py`: benchmark the model screening power. You also need target information, which is in `casf2016_benchmark/Targetinfo.dat`

The basic running scripts are following:
- `python casf2016_benchmark/scoring_power.py -f result_scoring_${epoch}.txt`
- `python casf2016_benchmark/ranking_power.py -f result_scoring_${epoch}.txt`
- `python casf2016_benchmark/docking_power.py -f result_docking_${epoch}.txt`
- `python casf2016_benchmark/screening_power.py -f result_screening_${epoch}.txt`

**Comment by isty2e** [comment]
I am sorry if my words were ambiguous. My original intention was about creating datasets for custom protein-ligand complexes (which are not in CASF-2016 or PDBBind) as per user input, and running inference on the dataset. The instructions in this repository, as far as I know, are limited to downloadable, given datasets.

**Comment by mseok** [comment]
We have no plans to disclose the data processing code.
Instead, you can follow several instructions in our paper.
For this work, we basically used `biopython` package to extract target pocket.

**Comment by isty2e** [comment]
Thanks for the answer. I suppose I can work on it myself.
